SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess Off
SecAuditEngine RelevantOnly
SecAuditLogFormat JSON
SecAuditLog /dev/stdout
SecAuditLogParts AHKZ
SecTmpDir /tmp
SecDataDir /tmp
SecUploadDir /tmp
SecUploadKeepFiles Off
SecRequestBodyLimit 16777216
SecRequestBodyNoFilesLimit 1048576

Include /etc/modsecurity.d/owasp-crs/crs-setup.conf
Include /etc/modsecurity.d/owasp-crs/rules/*.conf
