package com.stageaccord.sharedkernel.application;

public enum RejectionCode {
    IDEMPOTENCY_KEY_REQUIRED,
    VERSION_CONFLICT,
    DATABASE_UNAVAILABLE,
    SESSION_VALIDATION_UNAVAILABLE,
    AUDIT_UNAVAILABLE,
    FEATURE_WRITE_STOPPED,
    OBJECT_STORAGE_UNAVAILABLE,
    TIME_TRUST_UNAVAILABLE
}
