spring:
  config:
    activate:
      on-profile: worker
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${smtp-username}
    password: ${smtp-password}
    protocol: smtp
    test-connection: true
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.checkserveridentity: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 10000

server:
  address: 127.0.0.1
  port: 8081

stage-accord:
  worker:
    inbound-business-routes-enabled: false
